# Installing pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#Now let's import it

In [197]:
import pandas as pd

#Series and Dataframes
#  What is a Series?


A **Series** is a one-dimensional labeled array capable of holding any data type (integers, strings, floats, Python objects, etc).

Think of it as:
- A **single column** from a table
- A **list** with labels (called **index**)

In [198]:
data = [100, 200, 300]
s = pd.Series(data,name = 'series_1')

print("Series:\n", s)

Series:
 0    100
1    200
2    300
Name: series_1, dtype: int64

In [199]:
index = ["a", "b", "c"]
data = [10,20,30]
s = pd.Series(data, index=index) #index => identifier for rows

print("Series:\n", s)

Series:
 a    10
b    20
c    30
dtype: int64

## What is a DataFrame?

A **DataFrame** is a 2-dimensional table (like an Excel sheet or SQL table) with rows and columns.

- Think of it as a **collection of Series**
- Each column is a Series
- Rows and columns can have labels

In [200]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["NYC", "LA", "Chicago"]  #each key of a dict represent a column name and each element of a list represent a row
}

index = ["क", "ख", "ग"] #doesnt need to be unique but generally is made unique

df = pd.DataFrame(data,index)
print("DataFrame:\n", df)

DataFrame:
       Name  Age     City
क    Alice   25      NYC
ख      Bob   30       LA
ग  Charlie   35  Chicago

In [201]:
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]   #each element of the outer list represent a row and inner list represent column

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [202]:
data = [
    {"Name": "Alice", "Age": 25},
    {"Name": "Bob", "Age": 30},
    {"Name": "Charlie", "Age": 35}
]   #each element of the list represent a row and dict key:name of the column value:value of that column

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [203]:
s1 = pd.Series([25, 30, 35])
s2 = pd.Series(["Alice", "Bob", "Charlie"])


df = pd.DataFrame({
    "Name": s2,
    "Age": s1   #each series represent the data for a column
})

print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [321]:
person1 = pd.Series(["Alice", 25, "F"], index=["name", "age", "sex"])
person2 = pd.Series(["Bob", 30, "M"], index=["name", "age", "sex"])
person3 = pd.Series(["Charlie", 22, "M"], index=["name", "age", "sex"])

df = pd.DataFrame([person1, person2, person3])   #each series represent a row

print(df)

      name  age sex
0    Alice   25   F
1      Bob   30   M
2  Charlie   22   M

# Accessing columns
We can use df['column name'] to access columns of a dataframe

In [319]:
df['name']

0      Alice
1        Bob
2    Charlie
Name: name, dtype: object

In [320]:
type(df['name'])

pandas.core.series.Series

# Loading in Data

The first step in any ML problem is identifying what format your data is in, and then loading it into whatever framework you're using.

We're going to be looking at a sports dataset that shows the results from NCAA basketball games from 1985 to 2016. This dataset is in a CSV file, and the function we're going to use to read in the file is called **pd.read_csv()**. This function returns a **dataframe** variable.

The dataset contains the following columns:

Daynum: The day of the season the game was played.

Wteam: The team ID of the winning team.

Wscore: The score of the winning team.

Lteam: The team ID of the losing team.

Lscore: The score of the losing team.

Wloc: The location where the game was played (H for Home, A for Away, N for Neutral)

Numot: The number of overtime periods played.

In [401]:
df = pd.read_csv('RegularSeasonCompactResults.csv')

# The Basics

Now that we have our dataframe in our variable df, let's look at what it contains. We can use the function **head()** to see the first couple rows of the dataframe (or the function **tail()** to see the last few rows).

In [402]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
1    1985      25   1106    77.0   1354     NaN    H    NaN
2    1985      25   1112     NaN   1223     NaN    H    0.0
3    1985      25   1165    70.0   1432    54.0    H    0.0
4    1985      25   1192    86.0   1447    74.0    H    0.0

In [403]:
df.tail()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114    70.0   1419    50.0    N    0.0
145285    2016     132   1163    72.0   1272    58.0    N    0.0
145286    2016     132   1246    82.0   1401    77.0    N    1.0
145287    2016     132   1277    66.0   1345    62.0    N    0.0
145288    2016     132   1386    87.0   1433    74.0    N    0.0

We can see the dimensions of the dataframe using the the **shape** attribute

In [404]:
df.shape

(145289, 8)

We can also extract all the column names as a list, by using the **columns** attribute and can extract the rows with the **index** attribute

In [405]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In order to get a better idea of the type of data that we are dealing with, we can call the **describe()** function to see statistics like mean, min, etc about each column of the dataset.

In [406]:
df.describe()

,Season,Daynum,Wteam,Wscore,Lteam,Lscore,Numot
count,145289.000000,145289.000000,145289.000000,130716.000000,145289.000000,130715.000000,130761.000000
mean,2001.574834,75.223816,1286.720646,76.599858,1282.864064,64.486463,0.044486
std,9.233342,33.287418,104.570275,12.180251,104.829234,11.389853,0.248061
min,1985.000000,0.000000,1101.000000,34.000000,1101.000000,20.000000,0.000000
25%,1994.000000,47.000000,1198.000000,68.000000,1191.000000,57.000000,0.000000
50%,2002.000000,78.000000,1284.000000,76.000000,1280.000000,64.000000,0.000000
75%,2010.000000,103.000000,1379.000000,84.000000,1375.000000,72.000000,0.000000
max,2016.000000,132.000000,1464.000000,186.000000,1464.000000,150.000000,6.000000

Okay, so now let's looking at information that we want to extract from the dataframe. Let's say I wanted to know the max value of a certain column. The function **max()** will show you the maximum values of all columns

In [407]:
df.max()

Season     2016
Daynum      132
Wteam      1464
Wscore    186.0
Lteam      1464
Lscore    150.0
Wloc          N
Numot       6.0
dtype: object

Then, if you'd like to specifically get the max value for a particular column, you pass in the name of the column using the bracket indexing operator

In [408]:
df['Wscore'].max()

186.0

If you'd like to find the mean of the Losing teams' score.

In [409]:
df['Lscore'].mean()

np.float64(64.4864629155032)

But what if that's not enough? Let's say we want to actually see the game(row) where this max score happened. We can call the **argmax()** function to identify the row index

In [410]:
df['Wscore'].argmax()

np.int64(24970)

One of the most useful functions that you can call on certain columns in a dataframe is the **value_counts()** function. It shows how many times each item appears in the column. This particular command shows the number of games in each season

In [411]:
df['Season'].value_counts()

Season
2016    5369
2014    5362
2015    5354
2013    5320
2010    5263
2012    5253
2009    5249
2011    5246
2008    5163
2007    5043
2006    4757
2005    4675
2003    4616
2004    4571
2002    4555
2000    4519
2001    4467
1999    4222
1998    4167
1997    4155
1992    4127
1991    4123
1996    4122
1995    4077
1994    4060
1990    4045
1989    4037
1993    3982
1988    3955
1987    3915
1986    3783
1985    3737
Name: count, dtype: int64

# Acessing Values

Then, in order to get attributes about the game, we need to use the **iloc[]** indexer. The main idea is that you want to use it whenever you have the integer index of a certain row that you want to access. As per Pandas documentation, iloc is an "integer-location based indexing for selection by position."

In [412]:
print(df.iloc[24970])

Season     1991
Daynum       68
Wteam      1258
Wscore    186.0
Lteam      1109
Lscore    140.0
Wloc          H
Numot       0.0
Name: 24970, dtype: object

Note: Iloc is not a function!!! Its an object which implements an indexer class (having a \_\_getitem__ function). Let's look at a simple class having \_\_getitem__.

In [413]:
class dummyindexer:
    def __init__(self, data):
        self.data = data

    def __getitem__(self, key):
        print(f"Getting item at: {key}")
        if isinstance(key, tuple):
            row, col = key
            return self.data[row][col]
        else:
            return self.data[key]

data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

obj = dummyindexer(data)

print(obj[1])  # This calls obj.__getitem__(1) behind the scenes
print(obj[1, 2])    #This calls obj.__getitem((1,2))
print(obj.__getitem__((1,2)))

Getting item at: 1
[4, 5, 6]
Getting item at: (1, 2)
6
Getting item at: (1, 2)
6

In [414]:
print(df.iloc.__getitem__(24970))  #this gets called under the hood

Season     1991
Daynum       68
Wteam      1258
Wscore    186.0
Lteam      1109
Lscore    140.0
Wloc          H
Numot       0.0
Name: 24970, dtype: object

Let's take this a step further. Let's say you want to know the game with the highest scoring winning team (this is what we just calculated), but you then want to know how many points the losing team scored along with the daynum.

In [415]:
print(df.iloc[24970][['Lscore','Daynum']])
#or
print('\n\n')

print(df.iloc[24970, [5,1]])   #this only accepts integers

Lscore    140.0
Daynum       68
Name: 24970, dtype: object



Lscore    140.0
Daynum       68
Name: 24970, dtype: object

When you see data displayed in the above format, you're dealing with a Pandas **Series** object, not a dataframe object.

In [416]:
type(df.iloc[24970])

pandas.core.series.Series

In [417]:
print(df.iloc[24970].index)

Index(['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc',
       'Numot'],
      dtype='object')

The following is a summary of the 3 data structures in Pandas (Haven't ever really used Panels yet)

![](DataStructures.png)

When you want to access values in a Series, you'll want to just treat the Series like a Python dictionary, so you'd access the value according to its key (which is normally an integer index)

In [418]:
df.iloc[24970]['Lscore']

np.float64(140.0)

The other really important object in Pandas is **loc** . Contrary to iloc, which is an integer based indexing, loc is a "Purely label-location based indexer for selection by label". Since all the games are ordered from 0 to 145288, iloc and loc are going to be pretty interchangable in this type of dataset

In [419]:
df.iloc[:3]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
1    1985      25   1106    77.0   1354     NaN    H    NaN
2    1985      25   1112     NaN   1223     NaN    H    0.0

In [420]:
df.loc[:3]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
1    1985      25   1106    77.0   1354     NaN    H    NaN
2    1985      25   1112     NaN   1223     NaN    H    0.0
3    1985      25   1165    70.0   1432    54.0    H    0.0

Notice the slight difference in that iloc is exclusive of the second number, while loc is inclusive.

Below is an example of how you can use loc to acheive the same task as we did previously with iloc

In [421]:
df.loc[24970, 'Lscore']

np.float64(140.0)

A faster version uses the **at()** function. At() is really useful wheneever you know the row label and the column label of the particular value that you want to get.

In [422]:
df.at[24970, 'Lscore']

np.float64(140.0)

Let's look at a better example

In [423]:
data = {
    "Name": ["Alice", "Bob", "Charlie","Chris"],
    "Age": [25, 30, 35,32],
    "City": ["NYC", "LA", "Chicago","NYC"]
}

index = ["क", "ख","⭐" ,"ख"]     #making the indexes non unique for demonstration purposes

example_dataframe = pd.DataFrame(data,index)
print("DataFrame:\n", example_dataframe)

DataFrame:
       Name  Age     City
क    Alice   25      NYC
ख      Bob   30       LA
⭐  Charlie   35  Chicago
ख    Chris   32      NYC

In [424]:
example_dataframe.iloc[0]

Name    Alice
Age        25
City      NYC
Name: क, dtype: object

In [425]:
example_dataframe.loc["क"]

Name    Alice
Age        25
City      NYC
Name: क, dtype: object

In [426]:
example_dataframe.loc['ख']

    Name  Age City
ख    Bob   30   LA
ख  Chris   32  NYC

In [427]:
example_dataframe.loc["क":'⭐']

      Name  Age     City
क    Alice   25      NYC
ख      Bob   30       LA
⭐  Charlie   35  Chicago

In [428]:
example_dataframe.loc["क":"ख"] #doesn't work because of non-unique index (but if the non unique indexes were together, it would work)

KeyError: "Cannot get right slice bound for non-unique label: 'ख'"

In [429]:
example_dataframe.iloc[0:3]

      Name  Age     City
क    Alice   25      NYC
ख      Bob   30       LA
⭐  Charlie   35  Chicago

# Null values
We will encounter several missing values in our data. The .isnull() method in pandas checks each value in a DataFrame or Series and returns:


  True if the value is null (i.e., NaN, None, or missing)

  False if the value is not null

In [430]:
df.isnull()   #returns a dataframe containing true/false

        Season  Daynum  Wteam  Wscore  Lteam  Lscore   Wloc  Numot
0        False   False  False   False  False   False  False  False
1        False   False  False   False  False    True  False   True
2        False   False  False    True  False    True  False  False
3        False   False  False   False  False   False  False  False
4        False   False  False   False  False   False  False  False
...        ...     ...    ...     ...    ...     ...    ...    ...
145284   False   False  False   False  False   False  False  False
145285   False   False  False   False  False   False  False  False
145286   False   False  False   False  False   False  False  False
145287   False   False  False   False  False   False  False  False
145288   False   False  False   False  False   False  False  False

[145289 rows x 8 columns]

In [434]:
df.isnull().sum(axis=0) #sum the values of that dataframe (true=1 false =0)

Season    0
Daynum    0
Wteam     0
Wscore    0
Lteam     0
Lscore    0
Wloc      0
Numot     0
dtype: int64

For learning purposes, let's see what this does

In [435]:
df.isnull().sum(axis=1)

0         0
3         0
4         0
5         0
8         0
         ..
145284    0
145285    0
145286    0
145287    0
145288    0
Length: 105879, dtype: int64

For now, lets just delete the rows having null value in any column

In [433]:
df.dropna(inplace=True)  #inplace = true replaces that dataframe with the new dataframe (equivalent to df=df.dropna())

# Sorting

Let's say that we want to sort the dataframe in increasing order for the scores of the losing team

In [364]:
df.sort_values('Lscore').head()

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
89021     2006      44   1284    41.0   1343    21.0    A    0.0
49310     1997      66   1157    61.0   1204    21.0    H    0.0
103660    2009      26   1326    59.0   1359    22.0    H    0.0
85042     2005      66   1131    73.0   1216    22.0    H    0.0
71040     2002      61   1173    60.0   1275    23.0    H    0.0

# Filtering Rows Conditionally

Now, let's say we want to find all of the rows that satisy a particular condition. For example, we want to find all of the games where the winning team scored more than 150 points. The idea behind this command is you want to access the column 'Wscore' of the dataframe df (df['Wscore']), find which entries are above 150 (df['Wscore'] > 150), and then returns only those specific rows in a dataframe format (df[df['Wscore'] > 150]).

In [369]:
df['Wscore'] > 150   #returns a boolean series containing true/false

0         False
3         False
4         False
5         False
8         False
          ...
145284    False
145285    False
145286    False
145287    False
145288    False
Name: Wscore, Length: 105879, dtype: bool

In [371]:
df[df['Wscore']>150]   #we can use the mask to filter the dataframe

       Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
5269     1986      75   1258   151.0   1109   107.0    H    0.0
12046    1988      40   1328   152.0   1147    84.0    H    0.0
12355    1988      52   1328   151.0   1173    99.0    N    0.0
16040    1989      40   1328   152.0   1331   122.0    H    0.0
16853    1989      68   1258   162.0   1109   144.0    A    0.0
19653    1990      30   1328   173.0   1109   101.0    H    0.0
19971    1990      38   1258   152.0   1109   137.0    A    0.0
20022    1990      40   1116   166.0   1109   101.0    H    0.0
23582    1991      26   1318   152.0   1258   123.0    N    0.0
24341    1991      47   1328   172.0   1258   112.0    H    0.0
24970    1991      68   1258   186.0   1109   140.0    H    0.0
28687    1992      54   1261   159.0   1319    86.0    H    0.0
35023    1993     112   1380   155.0   1341    91.0    A    0.0
40060    1995      32   1375   156.0   1341   114.0    H    0.0
52600    1998      33   1395   153.0   1410    87.0    H    0.0

This also works if you have multiple conditions. Let's say we want to find out when the winning team scores more than 150 points and when the losing team scores below 100.

In [372]:
df[(df['Wscore'] > 150) & (df['Lscore'] < 100)]

       Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
12046    1988      40   1328   152.0   1147    84.0    H    0.0
12355    1988      52   1328   151.0   1173    99.0    N    0.0
28687    1992      54   1261   159.0   1319    86.0    H    0.0
35023    1993     112   1380   155.0   1341    91.0    A    0.0
52600    1998      33   1395   153.0   1410    87.0    H    0.0

#Map and apply

In pandas, `map()` and `apply()` are used to transform data by applying custom functions but they work differently and serve different purposes.

  `map()`
- Used with **Series** only.
- Applies a function **element-wise** to each value.
- Great for simple transformations.

In [445]:
transformed_wscore = df['Wscore'].map(lambda x: x/255)
# lambda syntax: lambda input: expression
# Each element in the Series is passed to the lambda function, and the result is returned in a new Series.

transformed_wscore

0         0.317647
3         0.274510
4         0.337255
5         0.309804
8         0.384314
            ...
145284    0.274510
145285    0.282353
145286    0.321569
145287    0.258824
145288    0.341176
Name: Wscore, Length: 105879, dtype: float64

 `apply()`

  - Can be used with Series or DataFrame.

  - For Series: behaves like map().

  - For DataFrames: can apply functions row-wise or column-wise using the axis argument.

In [451]:
score_diff = df.apply(lambda row: row['Wscore'] - row['Lscore'],axis=1)  #axis = 1 because axis=0 passes columns but we need to work with rows
score_diff

0         17.0
3         16.0
4         12.0
5          1.0
8         18.0
          ...
145284    20.0
145285    14.0
145286     5.0
145287     4.0
145288    13.0
Length: 105879, dtype: float64

Adding the new series to our dataframe

In [455]:
df['Difference']= score_diff
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Difference
0    1985      20   1228    81.0   1328    64.0    N    0.0        17.0
3    1985      25   1165    70.0   1432    54.0    H    0.0        16.0
4    1985      25   1192    86.0   1447    74.0    H    0.0        12.0
5    1985      25   1218    79.0   1337    78.0    H    0.0         1.0
8    1985      25   1260    98.0   1133    80.0    H    0.0        18.0

#Vector operations and broadcasting

Vector operations in pandas allow you to perform arithmetic or logical operations on entire Series or DataFrames at once, without writing explicit loops. These operations happen element-wise, meaning that the operation is applied independently to each matching element based on the index labels.

Broadcasting is a related concept where pandas automatically expands smaller objects to match the shape of larger ones during operations. For instance, when you add a scalar value to a DataFrame, pandas "broadcasts" the scalar across every element in the DataFrame, effectively performing the operation element-wise without you having to write explicit code for it.

In [456]:
#We can calculate the differnce of scores by using vector operations
difference_by_vector_operations = df['Wscore'] - df['Lscore']
difference_by_vector_operations

0         17.0
3         16.0
4         12.0
5          1.0
8         18.0
          ...
145284    20.0
145285    14.0
145286     5.0
145287     4.0
145288    13.0
Length: 105879, dtype: float64

In [458]:
#Let's divide the difference by 10
difference_by_vector_operations = difference_by_vector_operations/10 #this is also a vector operation. it broadcasts the scalar value so that all the elements are divided by 10
difference_by_vector_operations

0         0.17
3         0.16
4         0.12
5         0.01
8         0.18
          ...
145284    0.20
145285    0.14
145286    0.05
145287    0.04
145288    0.13
Length: 105879, dtype: float64

# Grouping

Another important function in Pandas is **groupby()**. This is a function that allows you to group entries by certain attributes (e.g Grouping entries by season) and then perform operations on them. The following function groups all the entries (games) on the same season  and finds the mean for each group.

In [469]:
df.groupby('Season')['Difference'].mean()

Season
1985    10.803466
1986    11.215905
1987    11.122751
1988    12.181661
1989    12.083899
1990    11.816650
1991    12.649883
1992    12.983367
1993    12.189768
1994    12.561200
1995    12.724710
1996    12.315513
1997    12.688454
1998    12.753968
1999    12.569026
2000    12.380334
2001    12.332613
2002    12.271995
2003    12.056683
2004    11.996999
2005    12.044911
2006    12.030172
2007    12.168619
2008    12.209321
2009    12.186853
2010    12.166932
2011    11.862250
2012    11.982161
2013    11.865073
2014    11.659172
2015    11.652230
2016    11.885751
Name: Difference, dtype: float64

This next command groups all the games with the same Wteam number and finds where how many times that specific team won at home, on the road, or at a neutral site

In [ ]:
df.groupby('Wteam')['Wloc'].value_counts().head(9)

Wteam  Wloc
1101   H        12
       A         3
       N         3
1102   H       204
       A        73
       N        32
1103   H       324
       A       153
       N        41
Name: Wloc, dtype: int64

Now, let's see the number of gaves won at home, away

In [475]:
df.groupby('Wloc').size()

Wloc
A    32281
H    62947
N    10651
dtype: int64

Each dataframe has a **values** attribute which is useful because it basically displays your dataframe in a numpy array style format

In [ ]:
df.values

array([[1985, 20, 1228, ..., 64, 'N', 0],
       [1985, 25, 1106, ..., 70, 'H', 0],
       [1985, 25, 1112, ..., 56, 'H', 0],
       ...,
       [2016, 132, 1246, ..., 77, 'N', 1],
       [2016, 132, 1277, ..., 62, 'N', 0],
       [2016, 132, 1386, ..., 74, 'N', 0]], dtype=object)

Now, you can simply just access elements like you would in an array.

In [ ]:
df.values[0][0]

1985

# Finding outliers
In this demonstration, we will use Interquartile range to find out the outliers.

- **Q1** = 25th percentile  
- **Q3** = 75th percentile  
- **IQR** = Q3 - Q1

Outliers are defined as data points that lie:

- **Below:** Q1 - 1.5 × IQR  
- **Above:** Q3 + 1.5 × IQR

Let's find the outliers in the 'Difference' column

In [478]:
Q1 = df['Difference'].quantile(0.25)
Q3 = df['Difference'].quantile(0.75)
IQR = Q3 - Q1
print('Q1: ',Q1)
print('Q3: ',Q3)

Q1:  5.0
Q3:  17.0

In [479]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [480]:
outliers = df[(df['Difference'] < lower_bound) | (df['Difference'] > upper_bound)]
print(outliers)

        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Difference
16        1985      26   1120    92.0   1391    50.0    H    0.0        42.0
25        1985      26   1196   106.0   1416    55.0    H    0.0        51.0
35        1985      26   1286   109.0   1186    64.0    H    0.0        45.0
42        1985      26   1375   104.0   1126    68.0    H    0.0        36.0
51        1985      26   1443    93.0   1121    57.0    H    0.0        36.0
...        ...     ...    ...     ...    ...     ...  ...    ...         ...
144701    2016     117   1321    98.0   1353    59.0    H    0.0        39.0
144916    2016     122   1372    95.0   1322    55.0    A    0.0        40.0
145010    2016     124   1308    83.0   1410    44.0    A    0.0        39.0
145146    2016     128   1397    97.0   1120    59.0    N    0.0        38.0
145245    2016     130   1372   104.0   1223    68.0    N    0.0        36.0

[2909 rows x 9 columns]

There are many ways to handle outliers. For this demo, we will just cap the outliers to the threshold

In [482]:
df['Difference'] = df['Difference'].clip(lower=lower_bound, upper=upper_bound)

In [483]:
outliers = df[(df['Difference'] < lower_bound) | (df['Difference'] > upper_bound)]
print(outliers)

Empty DataFrame
Columns: [Season, Daynum, Wteam, Wscore, Lteam, Lscore, Wloc, Numot, Difference]
Index: []

# More on extracting Rows and Columns

The bracket indexing operator is one way to extract certain columns from a dataframe.

In [374]:
df[['Wscore', 'Lscore']].head()

   Wscore  Lscore
0    81.0    64.0
3    70.0    54.0
4    86.0    74.0
5    79.0    78.0
8    98.0    80.0

Notice that you can acheive the same result by using the loc function. Loc is a veryyyy versatile function that can help you in a lot of accessing and extracting tasks.

In [377]:
df.loc[:, ['Wscore', 'Lscore']].head()

   Wscore  Lscore
0    81.0    64.0
3    70.0    54.0
4    86.0    74.0
5    79.0    78.0
8    98.0    80.0

Note the difference is the return types when you use brackets and when you use double brackets.

In [378]:
type(df['Wscore'])

pandas.core.series.Series

In [379]:
type(df[['Wscore']])

pandas.core.frame.DataFrame

In [385]:
df.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
3    1985      25   1165    70.0   1432    54.0    H    0.0
4    1985      25   1192    86.0   1447    74.0    H    0.0
5    1985      25   1218    79.0   1337    78.0    H    0.0
8    1985      25   1260    98.0   1133    80.0    H    0.0

You've seen before that you can access columns through df['col name']. You can access rows by using slicing operations.

In [394]:
df[0:3]  #if you give pandas slice, it will assume your'e accessing the rows. However df[0] doesnot work (unless you have a column named 0)

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
3    1985      25   1165    70.0   1432    54.0    H    0.0
4    1985      25   1192    86.0   1447    74.0    H    0.0

Here's an equivalent using iloc

In [398]:
df.iloc[0:3,:]

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228    81.0   1328    64.0    N    0.0
3    1985      25   1165    70.0   1432    54.0    H    0.0
4    1985      25   1192    86.0   1447    74.0    H    0.0

# Lots of Other Great Resources

Pandas has been around for a while and there are a lot of other good resources if you're still interested on getting the most out of this library.
* http://pandas.pydata.org/pandas-docs/stable/10min.html
* https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python
* http://www.gregreda.com/2013/10/26/intro-to-pandas-data-structures/
* https://www.dataquest.io/blog/pandas-python-tutorial/
* https://drive.google.com/file/d/0ByIrJAE4KMTtTUtiVExiUGVkRkE/view
* https://www.youtube.com/playlist?list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y